"use client";
import {useEffect,useRef,useState} from 'react';
import {JournalHeader} from '@/components/journey-library';
type Category='trips'|'coffee'|'food';
type Card={id:string;slug?:string;title:string;summary:string;city?:string;country?:string;visibility?:string;coverPhoto?:{storageKey:string;caption?:string|null}|null};
const labels={trips:'旅行故事',coffee:'咖啡記憶',food:'美食記事'};
export function CategoryCatalog({category,initialMode='public'}:{category:Category;initialMode?:'public'|'edit'}){
  const [mode,setMode]=useState(initialMode),[query,setQuery]=useState(''),[items,setItems]=useState<Card[]>([]),[total,setTotal]=useState(0),[more,setMore]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(''),[ready,setReady]=useState(false),[attempt,setAttempt]=useState(0);
  const initial=useRef(true),restoreY=useRef(0),restoreCount=useRef(12),activeRequest=useRef<AbortController|null>(null);
  const key=`travelos-category-${category}`;
  useEffect(()=>{let saved:{mode?:'public'|'edit';query?:string;scroll?:number;count?:number}|null=null;try{saved=JSON.parse(sessionStorage.getItem(key)||'null');}catch{}const params=new URLSearchParams(window.location.search);const selected=params.get('mode');setMode(selected==='edit'||selected==='public'?selected:initialMode==='edit'?'edit':saved?.mode??initialMode);setQuery(params.get('q')??saved?.query??'');restoreY.current=saved?.scroll??0;restoreCount.current=saved?.count??12;setReady(true);return()=>activeRequest.current?.abort();},[key,initialMode]);
  function remember(){try{if(category==="trips")sessionStorage.setItem("travelos-reader-origin","/trips");sessionStorage.setItem(key,JSON.stringify({mode,query,scroll:window.scrollY,count:items.length}));}catch{}}
  async function load(append=false){
    activeRequest.current?.abort();const controller=new AbortController();activeRequest.current=controller;setBusy(true);setError('');
    const params=new URLSearchParams({category,mode,q:query,offset:String(append?items.length:0),limit:String(initial.current?Math.min(500,Math.max(12,restoreCount.current)):12)});
    try{const response=await fetch(`${category==='trips'?'/api/categories/trips':'/api/notes/catalog'}?${params}`,{signal:controller.signal,cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'暫時未能讀取');setItems(current=>append?[...current,...data.items]:data.items);setTotal(data.total);setMore(data.hasMore);if(initial.current){initial.current=false;requestAnimationFrame(()=>window.scrollTo(0,restoreY.current));}}
    catch(reason){if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:'暫時未能讀取');}
    finally{if(!controller.signal.aborted)setBusy(false);}
  }
  useEffect(()=>{if(!ready)return;const timer=setTimeout(()=>void load(),query?250:0);return()=>{clearTimeout(timer);activeRequest.current?.abort();};},[ready,category,mode,query,attempt]);
  function changeMode(next:'edit'|'public'){if(next===mode)return;const url=new URL(window.location.href);url.searchParams.set("mode",next);window.history.replaceState(null,"",url);setMode(next);setItems([]);restoreY.current=0;initial.current=false;try{sessionStorage.setItem(key,JSON.stringify({mode:next,query,scroll:0}));}catch{}}
  function href(item:Card){return category==='trips'?(mode==='edit'?`/trips/admin?trip=${encodeURIComponent(item.id)}`:`/trips/${item.slug}?id=${encodeURIComponent(item.id)}`):mode==='edit'?`/${category}/admin?id=${encodeURIComponent(item.id)}`:`/${category}/${item.slug}?id=${encodeURIComponent(item.id)}`;}
  return <main className="journal-site"><JournalHeader category={category}/><div className="jl-wrap"><section className="jl-intro"><h1>{labels[category]}</h1></section><section className="jl-collection"><div className="jl-tools"><div className="jl-filters" aria-label="目錄模式"><button type="button" aria-pressed={mode==='public'} onClick={()=>changeMode('public')}>公開閱讀</button><button type="button" aria-pressed={mode==='edit'} onClick={()=>changeMode('edit')}>全部・編輯</button></div><label className="jl-search"><input aria-label={`搜尋${labels[category]}`} type="search" placeholder="搜尋標題、地方或內容" value={query} onChange={e=>{setQuery(e.target.value);initial.current=false;}}/></label></div><div className="jl-section-heading"><span>{busy&&!items.length?"…":total} 篇{mode==='edit'?' · 包含草稿':''}</span>{mode==='edit'?<a className="jl-button" href={category==='trips'?'/trips/new':`/${category}/admin?new=1`} onClick={remember}>新增記事</a>:null}</div><div className="jl-grid">{items.map(item=><article className="jl-card" key={item.id}><a href={href(item)} onClick={remember}><div className="jl-card-image">{item.coverPhoto?<img src={item.coverPhoto.storageKey} alt={item.coverPhoto.caption||item.title} loading="lazy" decoding="async"/>:<span>{labels[category]}</span>}</div><div className="jl-card-copy"><p className="jl-eyebrow">{[item.country,item.city].filter(Boolean).join(' · ')}</p><h3>{item.title}</h3><p className="jl-card-summary">{item.summary}</p><div className="jl-card-foot"><span>{mode==='edit'?(item.visibility==='private'?'草稿':item.visibility==='public'?'已公開':'工作稿'):labels[category]}</span><span>{mode==='edit'?'編輯記事':'閱讀記事'} →</span></div></div></a></article>)}</div>{busy?<p role="status" className="jl-empty">正在讀取目錄…</p>:null}{error?<div role="alert" className="jl-empty"><p>{error}</p><button type="button" className="jl-button" onClick={()=>setAttempt(n=>n+1)}>重新讀取</button></div>:null}{!busy&&!error&&!items.length?<div className="jl-empty"><p>{query?'沒有符合的記事':mode==='edit'?'還沒有記事，可以從上方新增。':'目前沒有已公開的記事。'}</p></div>:null}{more&&!busy?<button type="button" className="jl-button" onClick={()=>void load(true)}>再看 12 篇</button>:null}</section></div></main>;
}



