import type { TripDetail, TripListItem } from "@/lib/types";

export const seedTripDetails: TripDetail[] = [
  {
    id: "trip_lapland_2020",
    userId: "user_travelos_owner",
    title: "拉普蘭冬日記憶 / Lapland Winter Journal",
    slug: "finland-lapland-winter-journal-2020",
    summary:
      "一段以羅瓦涅米為起點的芬蘭拉普蘭冬日旅程：聖誕老人村、北極圈、雪地木屋、篝火、雪橇與藍色天光，共同構成一種清澈、安靜、有距離感的冬季記憶。 / A winter journey through Finnish Lapland, anchored in Rovaniemi and shaped by Santa Claus Village, the Arctic Circle, snow cabins, campfire warmth, sled rides, and blue northern light.",
    country: "Finland",
    city: "Rovaniemi",
    startDate: "2020-01-18",
    endDate: "2020-01-25",
    visibility: "shared",
    rating: 5,
    totalCost: { amount: 4280, currency: "EUR" },
    coverPhotoId: "photo_lapland_santa_night",
    coordinates: { latitude: 66.5039, longitude: 25.7294 },
    createdAt: "2020-01-26T09:00:00.000Z",
    updatedAt: "2026-07-13T23:55:00.000Z",
    journalEntries: [
      {
        id: "journal_lapland_arrival",
        tripId: "trip_lapland_2020",
        title: "抵達北極圈以北 / Arrival above the Arctic Circle",
        body:
          "拉普蘭的冬天，有一種近乎克制的純淨。雪覆蓋了道路、屋頂和森林，也過濾掉了日常生活裡的雜音。抵達羅瓦涅米之後，時間的速度明顯慢了下來。這裡不是以熱鬧取勝的地方，而是用光線、寒冷、距離和安靜，重新調整人對世界的感知。\n\nLapland in winter carries an almost restrained purity. Snow covers roads, rooftops, and forests, filtering out the noise of everyday life. After arriving in Rovaniemi, time seemed to slow down. This is not a place that wins through spectacle; it works through light, cold, distance, and silence, gently recalibrating how we sense the world.",
        entryDate: "2020-01-18",
        mood: "清醒",
        weatherSummary: "寒冷，清澈，深雪",
        aiSummary: null,
        createdAt: "2020-01-18T20:30:00.000Z",
        updatedAt: "2020-01-18T20:30:00.000Z",
      },
      {
        id: "journal_lapland_santa",
        tripId: "trip_lapland_2020",
        title: "燈光亮起後的聖誕老人村 / Santa Claus Village after dusk",
        body:
          "聖誕老人村最動人的時刻，並不在白天，而在燈光亮起之後。建築、雪地、路標與櫥窗的暖光共同構成一種清晰的冬日秩序。它當然帶有童話色彩，但真正留下印象的，並不是童話本身，而是這種想像被放進真實地理之後所產生的微妙質感。\n\nSanta Claus Village is most moving after the lights come on. Buildings, snow paths, signs, and warm shop windows form a precise winter composition. It naturally carries a trace of fairytale, but what stays with me is not the fairytale itself. It is the subtle texture created when that childhood image is placed inside a real northern geography.",
        entryDate: "2020-01-20",
        mood: "靜謐",
        weatherSummary: "細雪，夜色漸深",
        aiSummary: null,
        createdAt: "2020-01-20T18:10:00.000Z",
        updatedAt: "2020-01-20T18:10:00.000Z",
      },
      {
        id: "journal_lapland_campfire",
        tripId: "trip_lapland_2020",
        title: "雪地裡的篝火 / Campfire in the snow",
        body:
          "在拉普蘭，溫暖不是抽象的詞。它可能是一團火、一盞燈、一間木屋，或是寒冷中靠近彼此的片刻。雪地裡的篝火沒有複雜的敘事，卻有很強的現場感。火光、白雪、呼吸和沉默，讓這一刻從普通行程裡脫離出來，成為真正可被記住的部分。\n\nIn Lapland, warmth is not an abstract word. It can be a small fire, a lamp, a wooden cabin, or a moment of standing closer together in the cold. The campfire in the snow needed no complicated story, yet it had a strong sense of presence. Firelight, white snow, visible breath, and quiet made this moment rise out of the itinerary and become a real memory.",
        entryDate: "2020-01-22",
        mood: "沉靜",
        weatherSummary: "極冷，無風",
        aiSummary: null,
        createdAt: "2020-01-22T21:00:00.000Z",
        updatedAt: "2020-01-22T21:00:00.000Z",
      },
    ],
    photos: [
      {
        id: "photo_lapland_santa_night",
        tripId: "trip_lapland_2020",
        storageKey: "/travelos/lapland/santa-village-night.jpeg",
        originalFilename: "santa-village-night.jpeg",
        caption: "夜色中的聖誕老人村，雪地與燈光形成溫暖的冬日秩序。 / Santa Claus Village at night, where snow and lights create a quiet winter order.",
        takenAt: "2020-01-20T18:20:00.000Z",
        coordinates: { latitude: 66.5436, longitude: 25.8472 },
        cameraMake: null,
        cameraModel: null,
        createdAt: "2020-01-20T18:25:00.000Z",
      },
      {
        id: "photo_lapland_arctic_circle",
        tripId: "trip_lapland_2020",
        storageKey: "/travelos/lapland/arctic-circle.jpeg",
        originalFilename: "arctic-circle.jpeg",
        caption: "羅瓦涅米附近的北極圈標記，是這趟旅程最清晰的地理座標。 / The Arctic Circle marker near Rovaniemi, the clearest geographic anchor of the journey.",
        takenAt: "2020-01-20T13:30:00.000Z",
        coordinates: { latitude: 66.5436, longitude: 25.8472 },
        cameraMake: null,
        cameraModel: null,
        createdAt: "2020-01-20T13:40:00.000Z",
      },
      {
        id: "photo_lapland_sled",
        tripId: "trip_lapland_2020",
        storageKey: "/travelos/lapland/sled.jpeg",
        originalFilename: "sled.jpeg",
        caption: "雪原上的雪橇路線，讓冬天從風景變成了身體裡的經驗。 / A sled route through the snowfields, turning winter from scenery into physical experience.",
        takenAt: "2020-01-21T15:10:00.000Z",
        coordinates: null,
        cameraMake: null,
        cameraModel: null,
        createdAt: "2020-01-21T15:20:00.000Z",
      },
      {
        id: "photo_lapland_campfire",
        tripId: "trip_lapland_2020",
        storageKey: "/travelos/lapland/campfire.jpeg",
        originalFilename: "campfire.jpeg",
        caption: "寒冷夜晚裡的篝火，構成拉普蘭最真實的溫度。 / Campfire warmth on a cold Lapland evening.",
        takenAt: "2020-01-22T20:15:00.000Z",
        coordinates: null,
        cameraMake: null,
        cameraModel: null,
        createdAt: "2020-01-22T20:30:00.000Z",
      },
      {
        id: "photo_lapland_snow_cabin",
        tripId: "trip_lapland_2020",
        storageKey: "/travelos/lapland/snow-cabin.jpeg",
        originalFilename: "snow-cabin.jpeg",
        caption: "被新雪包圍的木屋，安靜得像一段被保存下來的時間。 / A wooden cabin surrounded by fresh snow, quiet enough to feel like preserved time.",
        takenAt: "2020-01-23T11:00:00.000Z",
        coordinates: null,
        cameraMake: null,
        cameraModel: null,
        createdAt: "2020-01-23T11:15:00.000Z",
      },
      {
        id: "photo_lapland_winter_village",
        tripId: "trip_lapland_2020",
        storageKey: "/travelos/lapland/winter-village.jpeg",
        originalFilename: "winter-village.jpeg",
        caption: "冬日村莊的屋頂與雪路，保留著北極圈以北特有的清澈。 / Winter village roofs and snow paths with the clarity of the far north.",
        takenAt: "2020-01-24T16:45:00.000Z",
        coordinates: null,
        cameraMake: null,
        cameraModel: null,
        createdAt: "2020-01-24T17:00:00.000Z",
      },
    ],
    places: [
      {
        id: "place_lapland_santa_village",
        tripId: "trip_lapland_2020",
        type: "attraction",
        name: "Santa Claus Village",
        country: "Finland",
        city: "Rovaniemi",
        address: "Tähtikuja 1, 96930 Rovaniemi",
        coordinates: { latitude: 66.5436, longitude: 25.8472 },
        rating: 5,
        notes: "傍晚燈光亮起後最有質感，雪地、建築和櫥窗的暖光共同形成完整的冬日畫面。",
        createdAt: "2020-01-20T18:00:00.000Z",
        updatedAt: "2020-01-20T18:00:00.000Z",
      },
      {
        id: "place_lapland_arctic_circle",
        tripId: "trip_lapland_2020",
        type: "attraction",
        name: "Arctic Circle Line",
        country: "Finland",
        city: "Rovaniemi",
        address: "Santa Claus Village",
        coordinates: { latitude: 66.5436, longitude: 25.8472 },
        rating: 5,
        notes: "一條簡單的地理線，卻讓人意識到自己已經離熟悉的生活半徑很遠。",
        createdAt: "2020-01-20T13:00:00.000Z",
        updatedAt: "2020-01-20T13:00:00.000Z",
      },
      {
        id: "place_lapland_cabin",
        tripId: "trip_lapland_2020",
        type: "hotel",
        name: "Snow cabin base",
        country: "Finland",
        city: "Rovaniemi",
        address: null,
        coordinates: null,
        rating: 5,
        notes: "適合慢下來的冬日基地：清晨、雪路、木屋燈光，以及出行間隙的溫暖。",
        createdAt: "2020-01-18T18:00:00.000Z",
        updatedAt: "2020-01-18T18:00:00.000Z",
      },
    ],
    costs: [
      {
        id: "cost_lapland_flights",
        tripId: "trip_lapland_2020",
        category: "flight",
        amount: 1560,
        currency: "EUR",
        paidAt: "2020-01-18",
        merchant: "Flights to Rovaniemi",
        notes: "Main family flight segment into Finnish Lapland.",
        createdAt: "2020-01-18T12:00:00.000Z",
      },
      {
        id: "cost_lapland_lodging",
        tripId: "trip_lapland_2020",
        category: "hotel",
        amount: 1720,
        currency: "EUR",
        paidAt: "2020-01-25",
        merchant: "Lapland cabin stay",
        notes: "Winter cabin lodging for the main trip window.",
        createdAt: "2020-01-25T11:00:00.000Z",
      },
      {
        id: "cost_lapland_activities",
        tripId: "trip_lapland_2020",
        category: "attraction",
        amount: 640,
        currency: "EUR",
        paidAt: "2020-01-24",
        merchant: "Village and sled activities",
        notes: "Santa Village, sled ride, winter activities, and local transfers.",
        createdAt: "2020-01-24T18:00:00.000Z",
      },
    ],
  },
  {
    id: "trip_hokkaido_2025",
    userId: "user_travelos_owner",
    title: "Northern Lights of Hokkaido",
    slug: "northern-lights-hokkaido-2025",
    summary:
      "A slow autumn route through seafood markets, hot springs, coastal rail towns, and wide-open national parks.",
    country: "Japan",
    city: "Sapporo",
    startDate: "2025-10-04",
    endDate: "2025-10-17",
    visibility: "private",
    rating: 5,
    totalCost: { amount: 2860, currency: "USD" },
    coverPhotoId: null,
    coordinates: { latitude: 43.0618, longitude: 141.3545 },
    createdAt: "2025-10-18T09:00:00.000Z",
    updatedAt: "2025-10-21T16:30:00.000Z",
    journalEntries: [
      {
        id: "journal_hokkaido_market",
        tripId: "trip_hokkaido_2025",
        title: "Nijo Market breakfast",
        body: "Arrived before the tour buses and had a quiet counter seat for crab soup, rice, and scallops. Marked this as the first morning worth repeating.",
        entryDate: "2025-10-05",
        mood: "Rested",
        weatherSummary: "Clear and cool",
        aiSummary: null,
        createdAt: "2025-10-05T08:30:00.000Z",
        updatedAt: "2025-10-05T08:30:00.000Z",
      },
      {
        id: "journal_hokkaido_onsen",
        tripId: "trip_hokkaido_2025",
        title: "Onsen after the coastal train",
        body: "The rail segment was slower than planned, but the evening bath reset the whole day. Add transit padding next time.",
        entryDate: "2025-10-10",
        mood: "Quiet",
        weatherSummary: "Light rain",
        aiSummary: null,
        createdAt: "2025-10-10T21:10:00.000Z",
        updatedAt: "2025-10-10T21:10:00.000Z",
      },
    ],
    photos: [
      {
        id: "photo_hokkaido_market",
        tripId: "trip_hokkaido_2025",
        storageKey: "placeholder/hokkaido-market.jpg",
        originalFilename: "hokkaido-market.jpg",
        caption: "Morning seafood counter at Nijo Market.",
        takenAt: "2025-10-05T08:12:00.000Z",
        coordinates: { latitude: 43.0584, longitude: 141.3554 },
        cameraMake: null,
        cameraModel: null,
        createdAt: "2025-10-05T08:20:00.000Z",
      },
      {
        id: "photo_hokkaido_coast",
        tripId: "trip_hokkaido_2025",
        storageKey: "placeholder/hokkaido-coast.jpg",
        originalFilename: "hokkaido-coast.jpg",
        caption: "Grey shoreline from the local train.",
        takenAt: "2025-10-10T15:40:00.000Z",
        coordinates: null,
        cameraMake: null,
        cameraModel: null,
        createdAt: "2025-10-10T16:05:00.000Z",
      },
    ],
    places: [
      {
        id: "place_hokkaido_hotel",
        tripId: "trip_hokkaido_2025",
        type: "hotel",
        name: "Sapporo base hotel",
        country: "Japan",
        city: "Sapporo",
        address: "Chuo Ward, Sapporo",
        coordinates: { latitude: 43.0579, longitude: 141.3544 },
        rating: 4,
        notes: "Good transit access and breakfast; rooms were compact but quiet.",
        createdAt: "2025-10-04T18:00:00.000Z",
        updatedAt: "2025-10-04T18:00:00.000Z",
      },
      {
        id: "place_hokkaido_nijo",
        tripId: "trip_hokkaido_2025",
        type: "restaurant",
        name: "Nijo Market counter",
        country: "Japan",
        city: "Sapporo",
        address: "Nijo Market",
        coordinates: { latitude: 43.0584, longitude: 141.3554 },
        rating: 5,
        notes: "Best early breakfast; return before 8:30.",
        createdAt: "2025-10-05T09:00:00.000Z",
        updatedAt: "2025-10-05T09:00:00.000Z",
      },
    ],
    costs: [
      {
        id: "cost_hokkaido_hotel",
        tripId: "trip_hokkaido_2025",
        category: "hotel",
        amount: 1180,
        currency: "USD",
        paidAt: "2025-10-04",
        merchant: "Sapporo base hotel",
        notes: "Two-city split lodging total.",
        createdAt: "2025-10-04T18:00:00.000Z",
      },
      {
        id: "cost_hokkaido_food",
        tripId: "trip_hokkaido_2025",
        category: "food",
        amount: 420,
        currency: "USD",
        paidAt: "2025-10-17",
        merchant: null,
        notes: "Markets, cafes, and seafood dinners.",
        createdAt: "2025-10-17T20:00:00.000Z",
      },
    ],
  },
  {
    id: "trip_bangkok_2025",
    userId: "user_travelos_owner",
    title: "Bangkok Food Notes",
    slug: "bangkok-food-notes-2025",
    summary:
      "Street food, hotel scouting, river neighborhoods, market mornings, and day trips built around local recommendations.",
    country: "Thailand",
    city: "Bangkok",
    startDate: "2025-03-12",
    endDate: "2025-03-22",
    visibility: "private",
    rating: 4,
    totalCost: { amount: 1840, currency: "USD" },
    coverPhotoId: null,
    coordinates: { latitude: 13.7563, longitude: 100.5018 },
    createdAt: "2025-03-23T12:00:00.000Z",
    updatedAt: "2025-03-24T09:00:00.000Z",
    journalEntries: [
      {
        id: "journal_bangkok_market",
        tripId: "trip_bangkok_2025",
        title: "Market morning checklist",
        body: "Saved stall names, rough prices, and best arrival times. The most useful notes were practical rather than poetic.",
        entryDate: "2025-03-14",
        mood: "Curious",
        weatherSummary: "Humid",
        aiSummary: null,
        createdAt: "2025-03-14T11:00:00.000Z",
        updatedAt: "2025-03-14T11:00:00.000Z",
      },
    ],
    photos: [
      {
        id: "photo_bangkok_river",
        tripId: "trip_bangkok_2025",
        storageKey: "placeholder/bangkok-river.jpg",
        originalFilename: "bangkok-river.jpg",
        caption: "River route after lunch.",
        takenAt: "2025-03-16T15:20:00.000Z",
        coordinates: { latitude: 13.7437, longitude: 100.4889 },
        cameraMake: null,
        cameraModel: null,
        createdAt: "2025-03-16T15:25:00.000Z",
      },
    ],
    places: [
      {
        id: "place_bangkok_hotel",
        tripId: "trip_bangkok_2025",
        type: "hotel",
        name: "Riverside hotel candidate",
        country: "Thailand",
        city: "Bangkok",
        address: "Charoen Krung Road",
        coordinates: { latitude: 13.722, longitude: 100.514 },
        rating: 4,
        notes: "Strong location for boats, weaker for late-night train access.",
        createdAt: "2025-03-12T16:00:00.000Z",
        updatedAt: "2025-03-12T16:00:00.000Z",
      },
    ],
    costs: [
      {
        id: "cost_bangkok_food",
        tripId: "trip_bangkok_2025",
        category: "food",
        amount: 310,
        currency: "USD",
        paidAt: "2025-03-22",
        merchant: null,
        notes: "Street food, cafes, and two planned dinners.",
        createdAt: "2025-03-22T20:00:00.000Z",
      },
    ],
  },
  {
    id: "trip_paris_2024",
    userId: "user_travelos_owner",
    title: "Winter Museum Walks",
    slug: "winter-museum-walks-paris-2024",
    summary:
      "A compact winter stay organized around museums, cafe notes, quiet side streets, and favorite neighborhood routes.",
    country: "France",
    city: "Paris",
    startDate: "2024-12-02",
    endDate: "2024-12-10",
    visibility: "private",
    rating: 5,
    totalCost: { amount: 2410, currency: "EUR" },
    coverPhotoId: null,
    coordinates: { latitude: 48.8566, longitude: 2.3522 },
    createdAt: "2024-12-11T10:00:00.000Z",
    updatedAt: "2024-12-12T13:30:00.000Z",
    journalEntries: [
      {
        id: "journal_paris_museum",
        tripId: "trip_paris_2024",
        title: "Small museum day",
        body: "The smaller galleries were better for winter pacing than the major stops. Keep the morning unscheduled next time.",
        entryDate: "2024-12-05",
        mood: "Settled",
        weatherSummary: "Cold and dry",
        aiSummary: null,
        createdAt: "2024-12-05T18:30:00.000Z",
        updatedAt: "2024-12-05T18:30:00.000Z",
      },
    ],
    photos: [
      {
        id: "photo_paris_cafe",
        tripId: "trip_paris_2024",
        storageKey: "placeholder/paris-cafe.jpg",
        originalFilename: "paris-cafe.jpg",
        caption: "Cafe table notes between museums.",
        takenAt: "2024-12-06T14:00:00.000Z",
        coordinates: null,
        cameraMake: null,
        cameraModel: null,
        createdAt: "2024-12-06T14:05:00.000Z",
      },
    ],
    places: [
      {
        id: "place_paris_cafe",
        tripId: "trip_paris_2024",
        type: "restaurant",
        name: "Left Bank cafe note",
        country: "France",
        city: "Paris",
        address: null,
        coordinates: null,
        rating: 5,
        notes: "Good reading stop, not too loud in the afternoon.",
        createdAt: "2024-12-06T15:00:00.000Z",
        updatedAt: "2024-12-06T15:00:00.000Z",
      },
    ],
    costs: [
      {
        id: "cost_paris_museums",
        tripId: "trip_paris_2024",
        category: "attraction",
        amount: 180,
        currency: "EUR",
        paidAt: "2024-12-10",
        merchant: null,
        notes: "Museum entries and timed reservations.",
        createdAt: "2024-12-10T20:00:00.000Z",
      },
    ],
  },
  {
    id: "trip_london_2024",
    userId: "user_travelos_owner",
    title: "London Transit Weekend",
    slug: "london-transit-weekend-2024",
    summary:
      "A long weekend for galleries, bookstores, rail experiments, hotel comparisons, and rainy evening journal entries.",
    country: "United Kingdom",
    city: "London",
    startDate: "2024-05-24",
    endDate: "2024-05-28",
    visibility: "private",
    rating: 4,
    totalCost: { amount: 1320, currency: "GBP" },
    coverPhotoId: null,
    coordinates: { latitude: 51.5072, longitude: -0.1276 },
    createdAt: "2024-05-29T10:00:00.000Z",
    updatedAt: "2024-05-30T10:00:00.000Z",
    journalEntries: [
      {
        id: "journal_london_rail",
        tripId: "trip_london_2024",
        title: "Rail routing notes",
        body: "The transit experiment worked, but luggage made two station changes annoying. Save lighter routes for the next pass.",
        entryDate: "2024-05-25",
        mood: "Focused",
        weatherSummary: "Rain",
        aiSummary: null,
        createdAt: "2024-05-25T20:00:00.000Z",
        updatedAt: "2024-05-25T20:00:00.000Z",
      },
    ],
    photos: [
      {
        id: "photo_london_bookshop",
        tripId: "trip_london_2024",
        storageKey: "placeholder/london-bookshop.jpg",
        originalFilename: "london-bookshop.jpg",
        caption: "Bookshop stop during the rain.",
        takenAt: "2024-05-26T16:20:00.000Z",
        coordinates: null,
        cameraMake: null,
        cameraModel: null,
        createdAt: "2024-05-26T16:30:00.000Z",
      },
    ],
    places: [
      {
        id: "place_london_gallery",
        tripId: "trip_london_2024",
        type: "attraction",
        name: "Rainy day gallery route",
        country: "United Kingdom",
        city: "London",
        address: null,
        coordinates: null,
        rating: 4,
        notes: "Good fallback route when walking plans collapse.",
        createdAt: "2024-05-26T17:00:00.000Z",
        updatedAt: "2024-05-26T17:00:00.000Z",
      },
    ],
    costs: [
      {
        id: "cost_london_transit",
        tripId: "trip_london_2024",
        category: "transportation",
        amount: 160,
        currency: "GBP",
        paidAt: "2024-05-28",
        merchant: "TfL and rail",
        notes: "Local transit plus airport connection.",
        createdAt: "2024-05-28T18:00:00.000Z",
      },
    ],
  },
];

export const tripListItems: TripListItem[] = seedTripDetails.map((trip) => ({
  id: trip.id,
  title: trip.title,
  slug: trip.slug,
  summary: trip.summary,
  country: trip.country,
  city: trip.city,
  startDate: trip.startDate,
  endDate: trip.endDate,
  rating: trip.rating,
  totalCost: trip.totalCost,
  coverPhotoId: trip.coverPhotoId,
}));

export function getTripsByStartDate(): TripListItem[] {
  return [...tripListItems].sort((firstTrip, secondTrip) =>
    secondTrip.startDate.localeCompare(firstTrip.startDate),
  );
}

export function getTripDetailsByStartDate(): TripDetail[] {
  return [...seedTripDetails].sort((firstTrip, secondTrip) =>
    secondTrip.startDate.localeCompare(firstTrip.startDate),
  );
}

export function getTripDetailBySlug(slug: string): TripDetail | undefined {
  return seedTripDetails.find((trip) => trip.slug === slug);
}
